"""migration2

Revision ID: 5ea14ec0d65b
Revises: 4426bb69f4fe
Create Date: 2025-11-13 02:37:46.822726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea14ec0d65b'
down_revision: Union[str, Sequence[str], None] = '4426bb69f4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'metadata_json')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'subscription_id')
    # ### end Alembic commands ###
