"""migration3

Revision ID: ff5bf8287e43
Revises: 5ea14ec0d65b
Create Date: 2025-11-15 17:40:50.620827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5bf8287e43'
down_revision: Union[str, Sequence[str], None] = '5ea14ec0d65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('next_payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'next_payment_date')
    # ### end Alembic commands ###
